# To get started with Dependabot version updates, you'll need to specify which
# package ecosystems to update and where the package manifests are located.
# Please see the documentation for all configuration options:
# https://docs.github.com/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file

version: 2
updates:
  - package-ecosystem: "npm" # See documentation for possible values
    directory: "/" # Location of package manifests
    schedule:
      interval: "daily"
      time: "11:25"
      timezone: "Asia/Tokyo"
    groups:
      #dev-minor-patch-dependency-for-auto-marge:
      #  dependency-type: "development"
      #  update-types:
      #    - "minor"
      #    - "patch"
      prod-patch-dependency-auto-marge:
        dependency-type: "production"
        update-types:
          - "patch"
      #dev-major-dependency:
      #  dependency-type: "development"
      #  update-types:
      #    - "major"
      #prod-major-minor-dependency:
      #  dependency-type: "production"
      #  update-types:
      #    - "major"
      #    - "minor"
